--Personel Ve Maaş Yönetimi

-- CREATE TABLE Personeller
-- (
--     PersonelID INT PRIMARY KEY,
--     Ad nVARCHAR(50),
--     Soyad NVARCHAR(50),
--     Pozisyon NVARCHAR(10),
--     BaslangıcTarihi DATE
-- )
-- CREATE TABLE Maaslar
-- (
--     MaasID INT PRIMARY KEY,
--     PersonelID INT,
--     MaasMiktarı DECIMAL (10,2),
--     GüncellemeTarihi DATE,
--     FOREIGN KEY (PersonelID) REFERENCES Personeller (PersonelID),
-- )
-- INSERT INTO Personeller
--     (Ad, Soyad, Pozisyon, BaslangıcTarihi)
-- VALUES
--     ('Ahmet', 'Yılmaz', 'Müdür', '2015-09-01'),
--     ('Ayşe', 'Kara', 'Öğretmen', '2016-09-01'),
--     ('Mehmet', 'Demir', 'Öğretmen', '2017-09-01'),
--     ('Fatma', 'Çelik', 'Sekreter', '2018-09-01'),
--     ('Ali', 'Kaya', 'Öğretmen', '2019-09-01'),
--     ('Zeynep', 'Yavuz', 'Müdür Yardımcısı', '2020-09-01'),
--     ('Ebru', 'Polat', 'Öğretmen', '2021-09-01'),
--     ('Osman', 'Arslan', 'Sekreter', '2022-09-01'),
--     ('Seda', 'Güneş', 'Öğretmen', '2023-09-01'),
--     ('Can', 'Koç', 'Öğretmen', '2023-09-01');
-- INSERT INTO Maaslar
--     (PersonelID, MaasMiktarı, GüncellemeTarihi)
-- VALUES
--     (1, 10000, '2015-09-01'),
--     (2, 8000, '2016-09-01'),
--     (3, 7500, '2017-09-01'),
--     (4, 5000, '2018-09-01'),
--     (5, 7500, '2019-09-01'),
--     (6, 12000, '2020-09-01'),
--     (7, 8000, '2021-09-01'),
--     (8, 5000, '2022-09-01'),
--     (9, 7500, '2023-09-01'),
--     (10, 7500, '2023-09-01');
-- --SORGULAR
-- SELECT p.PersonelID, p.Ad, p.Soyad, p.Pozisyon, m.MaasMiktarı
-- FROM Personeller p JOIN Maaslar m  ONp.PersonelID=m.PersonelID
-- SELECT AVG(MaasMiktarı)
-- FROM Maaslar m
-- SELECT m.MAX(MaasMiktarı) , m.MIN(MaasMiktarı)
-- FROM Personeller p JOIN Maaslar m ON p.PersonelID=m.PersonelID
-- GROUP by p.Pozisyon
-- SELECT p.PersonelID AS [ID],
--     P.Ad AS [isim],
--     p.Soyad AS [Soyisim]
-- from Personeller p
-- GROUP BY p.PersonelID,p.Ad,p.Soyad
-- SELECT count(p.Pozisyon) as [personel sayısı]
-- from Personeller p
-- GROUP by p.Pozisyon ,COUNT(p.Pozisyon)
-- SELECT p.PersonelID,
--     p.Ad,
--     p.Soyad,
--     m.MaasMiktarı,
--     MAX(GüncellemeTarihi)
-- FROM Personeller p JOIN Maaslar m ON p.PersonelID=m.PersonelID
-- GROUP  BY p.Ad,
--  p.Soyad,
--  m.MaasMiktarı
-- ORDER BY p.PersonelID
-- SELECT p.PersonelID , p.Pozizyon
-- FROM Personeller p
-- WHERE p.Pozisyon='Öğretmen'
-- GROUP BY p.PersonelID,p.Pozisyon
-- SELECT p.PersonelID,
-- p.Ad,
-- P.Soyad,
-- AVG(MaasMiktarı)
-- FROM Maaslar m JOIN Personeller p ON m.PersonelID=p.PersonelID
-- GROUP BY p.PersonelID,
-- p.Ad,
-- P.Soyad 
-- SELECT
--     adi,
--     soyadi,
--     maas
-- FROM top 1
-- p.Ad,
-- p.Soyad,
-- m.MaasMiktarı
--    Personeller p  JOIN Maaslar m ON p.PersonelID=m.PersonelID
-- ORDER BY 
--     m.MaasMiktarı DESC
-- SELECT
--     PersonelID,
--     MaasMiktarı,
--     GüncellemeTarihi
-- FROM
--     Maaslar
-- WHERE 
--    PersonelID= 'Belirli_Personel_ID'
-- ORDER BY 
--     GüncellemeTarihi ASC;
-- SELECT
--     PersonelID,
--     MaasMiktarı,
--     GüncellemeTarihi
-- FROM
--     Maaslar
-- WHERE 
--    PersonelID = 'Belirli_Personel_ID'
-- ORDER BY 
--     GüncellemeTarihi ASC;

-- SELECT
--     PersonelID,
--     MaasMiktarı,
--     GüncellemeTarihi
--   FROM
--     Maaslar
-- WHERE 
--     GüncellemeTarihi >= DATEADD(MONTH, -6, GETDATE());








